
services:
  db:
    image: mysql:8.0.42
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pos_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: mysql://root:root@db:3306/pos_db
      NODE_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db_data: